# Generated by Django 4.2.14 on 2024-08-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSystem',
        ),
    ]
