# Generated by Django 4.2.14 on 2024-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hours',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='minutes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='seconds',
            field=models.IntegerField(),
        ),
    ]
