# Generated by Django 4.2.14 on 2024-08-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_activity_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersystem',
            name='email',
        ),
    ]
