# Generated by Django 4.2.14 on 2024-08-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usersystem_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usersystem'),
        ),
    ]
